// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: branch_product_transaction.proto

package sale_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrPrTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BranchId  string  `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	StaffId   string  `protobuf:"bytes,3,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	ProductId string  `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price     float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Typ       string  `protobuf:"bytes,6,opt,name=typ,proto3" json:"typ,omitempty"`
	Quantity  int64   `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedAt string  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt string  `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *BrPrTransaction) Reset() {
	*x = BrPrTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_product_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrPrTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrPrTransaction) ProtoMessage() {}

func (x *BrPrTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_branch_product_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrPrTransaction.ProtoReflect.Descriptor instead.
func (*BrPrTransaction) Descriptor() ([]byte, []int) {
	return file_branch_product_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *BrPrTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BrPrTransaction) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *BrPrTransaction) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *BrPrTransaction) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BrPrTransaction) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BrPrTransaction) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *BrPrTransaction) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BrPrTransaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BrPrTransaction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *BrPrTransaction) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type BrPrTrCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BranchId  string  `protobuf:"bytes,1,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	StaffId   string  `protobuf:"bytes,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	ProductId string  `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price     float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Typ       string  `protobuf:"bytes,5,opt,name=typ,proto3" json:"typ,omitempty"`
	Quantity  int64   `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *BrPrTrCreateReq) Reset() {
	*x = BrPrTrCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_product_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrPrTrCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrPrTrCreateReq) ProtoMessage() {}

func (x *BrPrTrCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_branch_product_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrPrTrCreateReq.ProtoReflect.Descriptor instead.
func (*BrPrTrCreateReq) Descriptor() ([]byte, []int) {
	return file_branch_product_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *BrPrTrCreateReq) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *BrPrTrCreateReq) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *BrPrTrCreateReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BrPrTrCreateReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BrPrTrCreateReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *BrPrTrCreateReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BrPrTrCreateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BrPrTrCreateResp) Reset() {
	*x = BrPrTrCreateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_product_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrPrTrCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrPrTrCreateResp) ProtoMessage() {}

func (x *BrPrTrCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_branch_product_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrPrTrCreateResp.ProtoReflect.Descriptor instead.
func (*BrPrTrCreateResp) Descriptor() ([]byte, []int) {
	return file_branch_product_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *BrPrTrCreateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BrPrTrGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit     int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	BranchId  string `protobuf:"bytes,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	StaffId   string `protobuf:"bytes,4,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	ProductId string `protobuf:"bytes,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Typ       string `protobuf:"bytes,6,opt,name=typ,proto3" json:"typ,omitempty"`
}

func (x *BrPrTrGetListReq) Reset() {
	*x = BrPrTrGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_product_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrPrTrGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrPrTrGetListReq) ProtoMessage() {}

func (x *BrPrTrGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_branch_product_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrPrTrGetListReq.ProtoReflect.Descriptor instead.
func (*BrPrTrGetListReq) Descriptor() ([]byte, []int) {
	return file_branch_product_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *BrPrTrGetListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BrPrTrGetListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BrPrTrGetListReq) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *BrPrTrGetListReq) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *BrPrTrGetListReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BrPrTrGetListReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

type BrPrTrGetListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrPrTransactions []*BrPrTransaction `protobuf:"bytes,1,rep,name=brPrTransactions,proto3" json:"brPrTransactions,omitempty"`
	Count            int64              `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BrPrTrGetListResp) Reset() {
	*x = BrPrTrGetListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_product_transaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrPrTrGetListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrPrTrGetListResp) ProtoMessage() {}

func (x *BrPrTrGetListResp) ProtoReflect() protoreflect.Message {
	mi := &file_branch_product_transaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrPrTrGetListResp.ProtoReflect.Descriptor instead.
func (*BrPrTrGetListResp) Descriptor() ([]byte, []int) {
	return file_branch_product_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *BrPrTrGetListResp) GetBrPrTransactions() []*BrPrTransaction {
	if x != nil {
		return x.BrPrTransactions
	}
	return nil
}

func (x *BrPrTrGetListResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BrPrTrIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BrPrTrIdReq) Reset() {
	*x = BrPrTrIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_product_transaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrPrTrIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrPrTrIdReq) ProtoMessage() {}

func (x *BrPrTrIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_branch_product_transaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrPrTrIdReq.ProtoReflect.Descriptor instead.
func (*BrPrTrIdReq) Descriptor() ([]byte, []int) {
	return file_branch_product_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *BrPrTrIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BrPrTrUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BranchId  string  `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	StaffId   string  `protobuf:"bytes,3,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	ProductId string  `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price     float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Typ       string  `protobuf:"bytes,6,opt,name=typ,proto3" json:"typ,omitempty"`
	Quantity  int64   `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *BrPrTrUpdateReq) Reset() {
	*x = BrPrTrUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_product_transaction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrPrTrUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrPrTrUpdateReq) ProtoMessage() {}

func (x *BrPrTrUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_branch_product_transaction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrPrTrUpdateReq.ProtoReflect.Descriptor instead.
func (*BrPrTrUpdateReq) Descriptor() ([]byte, []int) {
	return file_branch_product_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *BrPrTrUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BrPrTrUpdateReq) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *BrPrTrUpdateReq) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *BrPrTrUpdateReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BrPrTrUpdateReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BrPrTrUpdateReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *BrPrTrUpdateReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BrPrTrUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BrPrTrUpdateResp) Reset() {
	*x = BrPrTrUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_product_transaction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrPrTrUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrPrTrUpdateResp) ProtoMessage() {}

func (x *BrPrTrUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_branch_product_transaction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrPrTrUpdateResp.ProtoReflect.Descriptor instead.
func (*BrPrTrUpdateResp) Descriptor() ([]byte, []int) {
	return file_branch_product_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *BrPrTrUpdateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BrPrTrDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BrPrTrDeleteResp) Reset() {
	*x = BrPrTrDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_branch_product_transaction_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrPrTrDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrPrTrDeleteResp) ProtoMessage() {}

func (x *BrPrTrDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_branch_product_transaction_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrPrTrDeleteResp.ProtoReflect.Descriptor instead.
func (*BrPrTrDeleteResp) Descriptor() ([]byte, []int) {
	return file_branch_product_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *BrPrTrDeleteResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_branch_product_transaction_proto protoreflect.FileDescriptor

var file_branch_product_transaction_proto_rawDesc = []byte{
	0x0a, 0x20, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x99, 0x02, 0x0a, 0x0f, 0x42, 0x72, 0x50, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x79, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xac, 0x01, 0x0a,
	0x0f, 0x42, 0x72, 0x50, 0x72, 0x54, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x79, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x79, 0x70, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x24, 0x0a, 0x10, 0x42,
	0x72, 0x50, 0x72, 0x54, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0xa5, 0x01, 0x0a, 0x10, 0x42, 0x72, 0x50, 0x72, 0x54, 0x72, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x79, 0x70, 0x22, 0x74, 0x0a, 0x11, 0x42, 0x72, 0x50,
	0x72, 0x54, 0x72, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x49,
	0x0a, 0x10, 0x62, 0x72, 0x50, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x72, 0x50, 0x72, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x62, 0x72, 0x50, 0x72, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x1d, 0x0a, 0x0b, 0x42, 0x72, 0x50, 0x72, 0x54, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xbc,
	0x01, 0x0a, 0x0f, 0x42, 0x72, 0x50, 0x72, 0x54, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x79,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x24, 0x0a,
	0x10, 0x42, 0x72, 0x50, 0x72, 0x54, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x24, 0x0a, 0x10, 0x42, 0x72, 0x50, 0x72, 0x54, 0x72, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_branch_product_transaction_proto_rawDescOnce sync.Once
	file_branch_product_transaction_proto_rawDescData = file_branch_product_transaction_proto_rawDesc
)

func file_branch_product_transaction_proto_rawDescGZIP() []byte {
	file_branch_product_transaction_proto_rawDescOnce.Do(func() {
		file_branch_product_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_branch_product_transaction_proto_rawDescData)
	})
	return file_branch_product_transaction_proto_rawDescData
}

var file_branch_product_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_branch_product_transaction_proto_goTypes = []interface{}{
	(*BrPrTransaction)(nil),   // 0: sale_service.BrPrTransaction
	(*BrPrTrCreateReq)(nil),   // 1: sale_service.BrPrTrCreateReq
	(*BrPrTrCreateResp)(nil),  // 2: sale_service.BrPrTrCreateResp
	(*BrPrTrGetListReq)(nil),  // 3: sale_service.BrPrTrGetListReq
	(*BrPrTrGetListResp)(nil), // 4: sale_service.BrPrTrGetListResp
	(*BrPrTrIdReq)(nil),       // 5: sale_service.BrPrTrIdReq
	(*BrPrTrUpdateReq)(nil),   // 6: sale_service.BrPrTrUpdateReq
	(*BrPrTrUpdateResp)(nil),  // 7: sale_service.BrPrTrUpdateResp
	(*BrPrTrDeleteResp)(nil),  // 8: sale_service.BrPrTrDeleteResp
}
var file_branch_product_transaction_proto_depIdxs = []int32{
	0, // 0: sale_service.BrPrTrGetListResp.brPrTransactions:type_name -> sale_service.BrPrTransaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_branch_product_transaction_proto_init() }
func file_branch_product_transaction_proto_init() {
	if File_branch_product_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_branch_product_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrPrTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_product_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrPrTrCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_product_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrPrTrCreateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_product_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrPrTrGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_product_transaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrPrTrGetListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_product_transaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrPrTrIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_product_transaction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrPrTrUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_product_transaction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrPrTrUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_branch_product_transaction_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrPrTrDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_branch_product_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_branch_product_transaction_proto_goTypes,
		DependencyIndexes: file_branch_product_transaction_proto_depIdxs,
		MessageInfos:      file_branch_product_transaction_proto_msgTypes,
	}.Build()
	File_branch_product_transaction_proto = out.File
	file_branch_product_transaction_proto_rawDesc = nil
	file_branch_product_transaction_proto_goTypes = nil
	file_branch_product_transaction_proto_depIdxs = nil
}
