// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: staff_transaction.proto

package sale_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaffTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SaleId    string  `protobuf:"bytes,2,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	StaffId   string  `protobuf:"bytes,3,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Typ       string  `protobuf:"bytes,4,opt,name=typ,proto3" json:"typ,omitempty"`
	SourceTyp string  `protobuf:"bytes,5,opt,name=source_typ,json=sourceTyp,proto3" json:"source_typ,omitempty"`
	Amount    float32 `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	AboutText string  `protobuf:"bytes,7,opt,name=about_text,json=aboutText,proto3" json:"about_text,omitempty"`
	CreatedAt string  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt string  `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *StaffTransaction) Reset() {
	*x = StaffTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTransaction) ProtoMessage() {}

func (x *StaffTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_staff_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTransaction.ProtoReflect.Descriptor instead.
func (*StaffTransaction) Descriptor() ([]byte, []int) {
	return file_staff_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *StaffTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StaffTransaction) GetSaleId() string {
	if x != nil {
		return x.SaleId
	}
	return ""
}

func (x *StaffTransaction) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *StaffTransaction) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *StaffTransaction) GetSourceTyp() string {
	if x != nil {
		return x.SourceTyp
	}
	return ""
}

func (x *StaffTransaction) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StaffTransaction) GetAboutText() string {
	if x != nil {
		return x.AboutText
	}
	return ""
}

func (x *StaffTransaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StaffTransaction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *StaffTransaction) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type StaffTrCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaleId    string  `protobuf:"bytes,1,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	StaffId   string  `protobuf:"bytes,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Typ       string  `protobuf:"bytes,3,opt,name=typ,proto3" json:"typ,omitempty"`
	SourceTyp string  `protobuf:"bytes,4,opt,name=source_typ,json=sourceTyp,proto3" json:"source_typ,omitempty"`
	Amount    float32 `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	AboutText string  `protobuf:"bytes,6,opt,name=about_text,json=aboutText,proto3" json:"about_text,omitempty"`
}

func (x *StaffTrCreateReq) Reset() {
	*x = StaffTrCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTrCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTrCreateReq) ProtoMessage() {}

func (x *StaffTrCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_staff_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTrCreateReq.ProtoReflect.Descriptor instead.
func (*StaffTrCreateReq) Descriptor() ([]byte, []int) {
	return file_staff_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *StaffTrCreateReq) GetSaleId() string {
	if x != nil {
		return x.SaleId
	}
	return ""
}

func (x *StaffTrCreateReq) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *StaffTrCreateReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *StaffTrCreateReq) GetSourceTyp() string {
	if x != nil {
		return x.SourceTyp
	}
	return ""
}

func (x *StaffTrCreateReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StaffTrCreateReq) GetAboutText() string {
	if x != nil {
		return x.AboutText
	}
	return ""
}

type StaffTrCreateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StaffTrCreateResp) Reset() {
	*x = StaffTrCreateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTrCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTrCreateResp) ProtoMessage() {}

func (x *StaffTrCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_staff_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTrCreateResp.ProtoReflect.Descriptor instead.
func (*StaffTrCreateResp) Descriptor() ([]byte, []int) {
	return file_staff_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *StaffTrCreateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type StaffTrGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       int64   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit      int64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SaleId     string  `protobuf:"bytes,3,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	Typ        string  `protobuf:"bytes,4,opt,name=typ,proto3" json:"typ,omitempty"`
	StaffId    string  `protobuf:"bytes,5,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	AmountFrom float32 `protobuf:"fixed32,6,opt,name=amountFrom,proto3" json:"amountFrom,omitempty"`
	AmountTo   float32 `protobuf:"fixed32,7,opt,name=amountTo,proto3" json:"amountTo,omitempty"`
}

func (x *StaffTrGetListReq) Reset() {
	*x = StaffTrGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTrGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTrGetListReq) ProtoMessage() {}

func (x *StaffTrGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_staff_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTrGetListReq.ProtoReflect.Descriptor instead.
func (*StaffTrGetListReq) Descriptor() ([]byte, []int) {
	return file_staff_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *StaffTrGetListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *StaffTrGetListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *StaffTrGetListReq) GetSaleId() string {
	if x != nil {
		return x.SaleId
	}
	return ""
}

func (x *StaffTrGetListReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *StaffTrGetListReq) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *StaffTrGetListReq) GetAmountFrom() float32 {
	if x != nil {
		return x.AmountFrom
	}
	return 0
}

func (x *StaffTrGetListReq) GetAmountTo() float32 {
	if x != nil {
		return x.AmountTo
	}
	return 0
}

type StaffTrGetListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StaffTransactions []*StaffTransaction `protobuf:"bytes,1,rep,name=staffTransactions,proto3" json:"staffTransactions,omitempty"`
	Count             int64               `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *StaffTrGetListResp) Reset() {
	*x = StaffTrGetListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_transaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTrGetListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTrGetListResp) ProtoMessage() {}

func (x *StaffTrGetListResp) ProtoReflect() protoreflect.Message {
	mi := &file_staff_transaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTrGetListResp.ProtoReflect.Descriptor instead.
func (*StaffTrGetListResp) Descriptor() ([]byte, []int) {
	return file_staff_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *StaffTrGetListResp) GetStaffTransactions() []*StaffTransaction {
	if x != nil {
		return x.StaffTransactions
	}
	return nil
}

func (x *StaffTrGetListResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StaffTrIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StaffTrIdReq) Reset() {
	*x = StaffTrIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_transaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTrIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTrIdReq) ProtoMessage() {}

func (x *StaffTrIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_staff_transaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTrIdReq.ProtoReflect.Descriptor instead.
func (*StaffTrIdReq) Descriptor() ([]byte, []int) {
	return file_staff_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *StaffTrIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StaffTrUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SaleId    string  `protobuf:"bytes,2,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	StaffId   string  `protobuf:"bytes,3,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Typ       string  `protobuf:"bytes,4,opt,name=typ,proto3" json:"typ,omitempty"`
	SourceTyp string  `protobuf:"bytes,5,opt,name=source_typ,json=sourceTyp,proto3" json:"source_typ,omitempty"`
	Amount    float32 `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	AboutText string  `protobuf:"bytes,7,opt,name=about_text,json=aboutText,proto3" json:"about_text,omitempty"`
}

func (x *StaffTrUpdateReq) Reset() {
	*x = StaffTrUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_transaction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTrUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTrUpdateReq) ProtoMessage() {}

func (x *StaffTrUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_staff_transaction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTrUpdateReq.ProtoReflect.Descriptor instead.
func (*StaffTrUpdateReq) Descriptor() ([]byte, []int) {
	return file_staff_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *StaffTrUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StaffTrUpdateReq) GetSaleId() string {
	if x != nil {
		return x.SaleId
	}
	return ""
}

func (x *StaffTrUpdateReq) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *StaffTrUpdateReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *StaffTrUpdateReq) GetSourceTyp() string {
	if x != nil {
		return x.SourceTyp
	}
	return ""
}

func (x *StaffTrUpdateReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StaffTrUpdateReq) GetAboutText() string {
	if x != nil {
		return x.AboutText
	}
	return ""
}

type StaffTrUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StaffTrUpdateResp) Reset() {
	*x = StaffTrUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_transaction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTrUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTrUpdateResp) ProtoMessage() {}

func (x *StaffTrUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_staff_transaction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTrUpdateResp.ProtoReflect.Descriptor instead.
func (*StaffTrUpdateResp) Descriptor() ([]byte, []int) {
	return file_staff_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *StaffTrUpdateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type StaffTrDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StaffTrDeleteResp) Reset() {
	*x = StaffTrDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_transaction_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTrDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTrDeleteResp) ProtoMessage() {}

func (x *StaffTrDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_staff_transaction_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTrDeleteResp.ProtoReflect.Descriptor instead.
func (*StaffTrDeleteResp) Descriptor() ([]byte, []int) {
	return file_staff_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *StaffTrDeleteResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_staff_transaction_proto protoreflect.FileDescriptor

var file_staff_transaction_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x61, 0x6c, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x9b, 0x02, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x61, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x61, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x79, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x62, 0x6f,
	0x75, 0x74, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x62, 0x6f, 0x75, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xae, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x66, 0x66, 0x54,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x61,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x61, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x79, 0x70,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x62, 0x6f, 0x75, 0x74,
	0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x62, 0x6f,
	0x75, 0x74, 0x54, 0x65, 0x78, 0x74, 0x22, 0x25, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x66, 0x66, 0x54,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xbf, 0x01,
	0x0a, 0x11, 0x53, 0x74, 0x61, 0x66, 0x66, 0x54, 0x72, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x61, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x79, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x72, 0x6f,
	0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46,
	0x72, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x22,
	0x78, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x66, 0x66, 0x54, 0x72, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4c, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x66, 0x66, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x11, 0x73, 0x74, 0x61, 0x66, 0x66, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x54, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xbe, 0x01, 0x0a, 0x10, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x54, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x61, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x79, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x62, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x54, 0x65, 0x78, 0x74, 0x22, 0x25, 0x0a, 0x11, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x54, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x25, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x66, 0x66, 0x54, 0x72, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staff_transaction_proto_rawDescOnce sync.Once
	file_staff_transaction_proto_rawDescData = file_staff_transaction_proto_rawDesc
)

func file_staff_transaction_proto_rawDescGZIP() []byte {
	file_staff_transaction_proto_rawDescOnce.Do(func() {
		file_staff_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_staff_transaction_proto_rawDescData)
	})
	return file_staff_transaction_proto_rawDescData
}

var file_staff_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_staff_transaction_proto_goTypes = []interface{}{
	(*StaffTransaction)(nil),   // 0: sale_service.StaffTransaction
	(*StaffTrCreateReq)(nil),   // 1: sale_service.StaffTrCreateReq
	(*StaffTrCreateResp)(nil),  // 2: sale_service.StaffTrCreateResp
	(*StaffTrGetListReq)(nil),  // 3: sale_service.StaffTrGetListReq
	(*StaffTrGetListResp)(nil), // 4: sale_service.StaffTrGetListResp
	(*StaffTrIdReq)(nil),       // 5: sale_service.StaffTrIdReq
	(*StaffTrUpdateReq)(nil),   // 6: sale_service.StaffTrUpdateReq
	(*StaffTrUpdateResp)(nil),  // 7: sale_service.StaffTrUpdateResp
	(*StaffTrDeleteResp)(nil),  // 8: sale_service.StaffTrDeleteResp
}
var file_staff_transaction_proto_depIdxs = []int32{
	0, // 0: sale_service.StaffTrGetListResp.staffTransactions:type_name -> sale_service.StaffTransaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_staff_transaction_proto_init() }
func file_staff_transaction_proto_init() {
	if File_staff_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_staff_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTrCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTrCreateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTrGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_transaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTrGetListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_transaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTrIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_transaction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTrUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_transaction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTrUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_transaction_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTrDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staff_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_staff_transaction_proto_goTypes,
		DependencyIndexes: file_staff_transaction_proto_depIdxs,
		MessageInfos:      file_staff_transaction_proto_msgTypes,
	}.Build()
	File_staff_transaction_proto = out.File
	file_staff_transaction_proto_rawDesc = nil
	file_staff_transaction_proto_goTypes = nil
	file_staff_transaction_proto_depIdxs = nil
}
