// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: staff_tarif.proto

package staff_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaffTariff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Typ           string  `protobuf:"bytes,3,opt,name=typ,proto3" json:"typ,omitempty"`
	AmountForCash float32 `protobuf:"fixed32,4,opt,name=amount_for_cash,json=amountForCash,proto3" json:"amount_for_cash,omitempty"`
	AmountForCard float32 `protobuf:"fixed32,5,opt,name=amount_for_card,json=amountForCard,proto3" json:"amount_for_card,omitempty"`
	CreatedAt     string  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string  `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string  `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *StaffTariff) Reset() {
	*x = StaffTariff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_tarif_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffTariff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffTariff) ProtoMessage() {}

func (x *StaffTariff) ProtoReflect() protoreflect.Message {
	mi := &file_staff_tarif_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffTariff.ProtoReflect.Descriptor instead.
func (*StaffTariff) Descriptor() ([]byte, []int) {
	return file_staff_tarif_proto_rawDescGZIP(), []int{0}
}

func (x *StaffTariff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StaffTariff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffTariff) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *StaffTariff) GetAmountForCash() float32 {
	if x != nil {
		return x.AmountForCash
	}
	return 0
}

func (x *StaffTariff) GetAmountForCard() float32 {
	if x != nil {
		return x.AmountForCard
	}
	return 0
}

func (x *StaffTariff) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StaffTariff) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *StaffTariff) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type TariffCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Typ           string  `protobuf:"bytes,2,opt,name=typ,proto3" json:"typ,omitempty"`
	AmountForCash float32 `protobuf:"fixed32,3,opt,name=amount_for_cash,json=amountForCash,proto3" json:"amount_for_cash,omitempty"`
	AmountForCard float32 `protobuf:"fixed32,4,opt,name=amount_for_card,json=amountForCard,proto3" json:"amount_for_card,omitempty"`
}

func (x *TariffCreateReq) Reset() {
	*x = TariffCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_tarif_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TariffCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TariffCreateReq) ProtoMessage() {}

func (x *TariffCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_staff_tarif_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TariffCreateReq.ProtoReflect.Descriptor instead.
func (*TariffCreateReq) Descriptor() ([]byte, []int) {
	return file_staff_tarif_proto_rawDescGZIP(), []int{1}
}

func (x *TariffCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TariffCreateReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *TariffCreateReq) GetAmountForCash() float32 {
	if x != nil {
		return x.AmountForCash
	}
	return 0
}

func (x *TariffCreateReq) GetAmountForCard() float32 {
	if x != nil {
		return x.AmountForCard
	}
	return 0
}

type TariffCreateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TariffCreateResp) Reset() {
	*x = TariffCreateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_tarif_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TariffCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TariffCreateResp) ProtoMessage() {}

func (x *TariffCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_staff_tarif_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TariffCreateResp.ProtoReflect.Descriptor instead.
func (*TariffCreateResp) Descriptor() ([]byte, []int) {
	return file_staff_tarif_proto_rawDescGZIP(), []int{2}
}

func (x *TariffCreateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TariffGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Typ   string `protobuf:"bytes,3,opt,name=typ,proto3" json:"typ,omitempty"`
}

func (x *TariffGetListReq) Reset() {
	*x = TariffGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_tarif_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TariffGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TariffGetListReq) ProtoMessage() {}

func (x *TariffGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_staff_tarif_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TariffGetListReq.ProtoReflect.Descriptor instead.
func (*TariffGetListReq) Descriptor() ([]byte, []int) {
	return file_staff_tarif_proto_rawDescGZIP(), []int{3}
}

func (x *TariffGetListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TariffGetListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TariffGetListReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

type TariffGetListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tariffs []*StaffTariff `protobuf:"bytes,1,rep,name=tariffs,proto3" json:"tariffs,omitempty"`
	Count   int64          `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TariffGetListResp) Reset() {
	*x = TariffGetListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_tarif_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TariffGetListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TariffGetListResp) ProtoMessage() {}

func (x *TariffGetListResp) ProtoReflect() protoreflect.Message {
	mi := &file_staff_tarif_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TariffGetListResp.ProtoReflect.Descriptor instead.
func (*TariffGetListResp) Descriptor() ([]byte, []int) {
	return file_staff_tarif_proto_rawDescGZIP(), []int{4}
}

func (x *TariffGetListResp) GetTariffs() []*StaffTariff {
	if x != nil {
		return x.Tariffs
	}
	return nil
}

func (x *TariffGetListResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TariffIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TariffIdReq) Reset() {
	*x = TariffIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_tarif_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TariffIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TariffIdReq) ProtoMessage() {}

func (x *TariffIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_staff_tarif_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TariffIdReq.ProtoReflect.Descriptor instead.
func (*TariffIdReq) Descriptor() ([]byte, []int) {
	return file_staff_tarif_proto_rawDescGZIP(), []int{5}
}

func (x *TariffIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TariffUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Typ           string  `protobuf:"bytes,3,opt,name=typ,proto3" json:"typ,omitempty"`
	AmountForCash float32 `protobuf:"fixed32,4,opt,name=amount_for_cash,json=amountForCash,proto3" json:"amount_for_cash,omitempty"`
	AmountForCard float32 `protobuf:"fixed32,5,opt,name=amount_for_card,json=amountForCard,proto3" json:"amount_for_card,omitempty"`
}

func (x *TariffUpdateReq) Reset() {
	*x = TariffUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_tarif_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TariffUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TariffUpdateReq) ProtoMessage() {}

func (x *TariffUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_staff_tarif_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TariffUpdateReq.ProtoReflect.Descriptor instead.
func (*TariffUpdateReq) Descriptor() ([]byte, []int) {
	return file_staff_tarif_proto_rawDescGZIP(), []int{6}
}

func (x *TariffUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TariffUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TariffUpdateReq) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *TariffUpdateReq) GetAmountForCash() float32 {
	if x != nil {
		return x.AmountForCash
	}
	return 0
}

func (x *TariffUpdateReq) GetAmountForCard() float32 {
	if x != nil {
		return x.AmountForCard
	}
	return 0
}

type TariffUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TariffUpdateResp) Reset() {
	*x = TariffUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_tarif_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TariffUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TariffUpdateResp) ProtoMessage() {}

func (x *TariffUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_staff_tarif_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TariffUpdateResp.ProtoReflect.Descriptor instead.
func (*TariffUpdateResp) Descriptor() ([]byte, []int) {
	return file_staff_tarif_proto_rawDescGZIP(), []int{7}
}

func (x *TariffUpdateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TariffDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TariffDeleteResp) Reset() {
	*x = TariffDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_tarif_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TariffDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TariffDeleteResp) ProtoMessage() {}

func (x *TariffDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_staff_tarif_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TariffDeleteResp.ProtoReflect.Descriptor instead.
func (*TariffDeleteResp) Descriptor() ([]byte, []int) {
	return file_staff_tarif_proto_rawDescGZIP(), []int{8}
}

func (x *TariffDeleteResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_staff_tarif_proto protoreflect.FileDescriptor

var file_staff_tarif_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x74, 0x61, 0x72, 0x69, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0xf0, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x66, 0x66, 0x54, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x79, 0x70, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x73, 0x68,
	0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63,
	0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x79, 0x70, 0x12,
	0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x46, 0x6f, 0x72, 0x43, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x64, 0x22,
	0x24, 0x0a, 0x10, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4e, 0x0a, 0x10, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x74, 0x79, 0x70, 0x22, 0x5f, 0x0a, 0x11, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x07, 0x74, 0x61,
	0x72, 0x69, 0x66, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x07, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1d, 0x0a, 0x0b, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x79, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x79, 0x70, 0x12,
	0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61,
	0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x46, 0x6f, 0x72, 0x43, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x64, 0x22,
	0x24, 0x0a, 0x10, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x24, 0x0a, 0x10, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x18, 0x5a, 0x16, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staff_tarif_proto_rawDescOnce sync.Once
	file_staff_tarif_proto_rawDescData = file_staff_tarif_proto_rawDesc
)

func file_staff_tarif_proto_rawDescGZIP() []byte {
	file_staff_tarif_proto_rawDescOnce.Do(func() {
		file_staff_tarif_proto_rawDescData = protoimpl.X.CompressGZIP(file_staff_tarif_proto_rawDescData)
	})
	return file_staff_tarif_proto_rawDescData
}

var file_staff_tarif_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_staff_tarif_proto_goTypes = []interface{}{
	(*StaffTariff)(nil),       // 0: staff_service.StaffTariff
	(*TariffCreateReq)(nil),   // 1: staff_service.TariffCreateReq
	(*TariffCreateResp)(nil),  // 2: staff_service.TariffCreateResp
	(*TariffGetListReq)(nil),  // 3: staff_service.TariffGetListReq
	(*TariffGetListResp)(nil), // 4: staff_service.TariffGetListResp
	(*TariffIdReq)(nil),       // 5: staff_service.TariffIdReq
	(*TariffUpdateReq)(nil),   // 6: staff_service.TariffUpdateReq
	(*TariffUpdateResp)(nil),  // 7: staff_service.TariffUpdateResp
	(*TariffDeleteResp)(nil),  // 8: staff_service.TariffDeleteResp
}
var file_staff_tarif_proto_depIdxs = []int32{
	0, // 0: staff_service.TariffGetListResp.tariffs:type_name -> staff_service.StaffTariff
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_staff_tarif_proto_init() }
func file_staff_tarif_proto_init() {
	if File_staff_tarif_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_staff_tarif_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffTariff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_tarif_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TariffCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_tarif_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TariffCreateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_tarif_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TariffGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_tarif_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TariffGetListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_tarif_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TariffIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_tarif_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TariffUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_tarif_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TariffUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_tarif_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TariffDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staff_tarif_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_staff_tarif_proto_goTypes,
		DependencyIndexes: file_staff_tarif_proto_depIdxs,
		MessageInfos:      file_staff_tarif_proto_msgTypes,
	}.Build()
	File_staff_tarif_proto = out.File
	file_staff_tarif_proto_rawDesc = nil
	file_staff_tarif_proto_goTypes = nil
	file_staff_tarif_proto_depIdxs = nil
}
